## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  server:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 700Mi
  sentinel:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 200Mi

## Node labels and tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
nodeSelector: {}
tolerations: []

# Affinity per Pod type
affinity:
  servers: {}
  sentinels: {}

## Additional labels to set on all resources
extraLabels:
# mylabel: myvalue

## Redis image version
image: kumina/redis-ha-k8s:4.0.9-r0-5
## replicas number for each component
replicas:
  servers: 3
  sentinels: 3
servers:
  serviceType: ClusterIP  # [ClusterIP|LoadBalancer]
  annotations: {}

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

## Max memory to use for each redis instance. Default is unlimited.
maxMemory: ""
## The policy to use for clearing memory when hitting maxMemory. A full list can be found here:
## https://redis.io/topics/lru-cache#eviction-policies
maxMemoryPolicy: "noeviction"

## Configures redis with AUTH (requirepass & masterauth conf params)
auth: false

## Redis password
## Defaults to a random 10-character alphanumeric string if not set and auth is true
## ref: https://github.com/kubernetes/charts/blob/master/stable/redis-ha/templates/redis-auth-secret.yaml
##
## redisPassword:

## When persistent volumes are required, set these
persistentVolume:
  enabled: false
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  annotations: {}
