apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "redis-ha.fullname" . }}-sentinel-pdb
  labels:
{{ include "labels.standard" . | indent 4 }}
{{ toYaml .Values.extraLabels | indent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: "redis-ha"
      redis-role: "sentinel"
      release: "{{ .Release.Name }}"

