apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "redis-ha.fullname" . }}-sentinel-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: "redis-ha"
      redis-role: "sentinel"
      release: "{{ .Release.Name }}"
